### ISSUE TITLE
coin_apis.coins() function not work

### ISSUE THREAD

**Issue by mmmaaaggg** [lucaoflaif/pyCoinMarketCapAPI#7]
```python
for coin_istance in coin_apis.coins():
    print(coin_istance.coin_id, coin_istance.symbol, coin_istance.price_usd, coin_istance.percent_change_24h)
```
got exception:
_____
```bash
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "D:\WSPych\RefUtils\venv\lib\site-packages\coinmarketcapapi\__init__.py", line 28, in _return_all_coins
    for coin in self.cache.get_response(r_type='ticker'):
TypeError: 'NoneType' object is not iterable #
```

**Comment by lucaoflaif** [comment]
Did you call the ```send_request()``` method of the CoinMarketCapAPI class? It seems the cache is empty.
From the readme:
```
Okay, let's call the server:

coin_apis.send_request()
Thanks to this method we filled our class with new data and the Cache mechanism will be activated (See Cache mechanism), call this method is necessary for the first time in order to have data to work with.

You can pass to the send_request() method all the parameters allowed by the official APIs (See Public methods)
```
